# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Outfit < Formula
  desc "Configure opencode provider catalogues"
  homepage "https://github.com/lucinate-ai/outfit"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lucinate-ai/outfit/releases/download/v1.0.0/outfit_darwin_amd64.tar.gz"
      sha256 "5510e66d53955f2503678f4f92517a6ef2ccd04ebf54e82d84c81cd18909ba2f"

      define_method(:install) do
        bin.install "outfit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lucinate-ai/outfit/releases/download/v1.0.0/outfit_darwin_arm64.tar.gz"
      sha256 "a94b30c9750c68007b05ceb09ca51835ed291f2395bf991bb5984738815d7964"

      define_method(:install) do
        bin.install "outfit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucinate-ai/outfit/releases/download/v1.0.0/outfit_linux_amd64.tar.gz"
      sha256 "f1b193d5e52d0a1df7a3954be78439117baaf6e2fdbe51b5e295abe23ce7463f"
      define_method(:install) do
        bin.install "outfit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucinate-ai/outfit/releases/download/v1.0.0/outfit_linux_arm64.tar.gz"
      sha256 "6a99f32d77960935f3fc6dc9e65feb6306347e1849e24f20de144d8e14c88219"
      define_method(:install) do
        bin.install "outfit"
      end
    end
  end

  test do
    system "#{bin}/outfit", "--help"
  end
end
