# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Outfit < Formula
  desc "Configure opencode provider catalogues"
  homepage "https://github.com/lucinate-ai/outfit"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lucinate-ai/outfit/releases/download/v1.2.0/outfit_darwin_amd64.tar.gz"
      sha256 "121ccaac41f7adee990d4346fa3c6abd0bd22393683ae717ccbcc6cae00172bf"

      define_method(:install) do
        bin.install "outfit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lucinate-ai/outfit/releases/download/v1.2.0/outfit_darwin_arm64.tar.gz"
      sha256 "31a037e596914b5d3e211b617549e12b71e5bcf29053962cf6b1f5914ff49ea9"

      define_method(:install) do
        bin.install "outfit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucinate-ai/outfit/releases/download/v1.2.0/outfit_linux_amd64.tar.gz"
      sha256 "942d295f9b8d5c90debda9c74c97e7d2cdb873db9a02cc6f9fd05706aefb4550"
      define_method(:install) do
        bin.install "outfit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucinate-ai/outfit/releases/download/v1.2.0/outfit_linux_arm64.tar.gz"
      sha256 "90b71942ec4ec1dfcc40c720afe499f4bd2e35ee9fc213ee92e77132499a81e7"
      define_method(:install) do
        bin.install "outfit"
      end
    end
  end

  test do
    system "#{bin}/outfit", "--help"
  end
end
