# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Outfit < Formula
  desc "Configure opencode provider catalogues"
  homepage "https://github.com/lucinate-ai/outfit"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lucinate-ai/outfit/releases/download/v1.6.0/outfit_darwin_amd64.tar.gz"
      sha256 "ba3eae54566efe645cc62bc8b89c59b545a26e8b2c2a2e75d7fb9973f54f2911"

      define_method(:install) do
        bin.install "outfit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lucinate-ai/outfit/releases/download/v1.6.0/outfit_darwin_arm64.tar.gz"
      sha256 "b614320d591e6fbcc8cb2d4634343dd46576b62fea411d8ebac72630237e392d"

      define_method(:install) do
        bin.install "outfit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucinate-ai/outfit/releases/download/v1.6.0/outfit_linux_amd64.tar.gz"
      sha256 "bc70417e6727fb67c41c11b5ae7999d3558233ff222d07addcbea4d2f813766e"
      define_method(:install) do
        bin.install "outfit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucinate-ai/outfit/releases/download/v1.6.0/outfit_linux_arm64.tar.gz"
      sha256 "e715203628fd303844d594974dfec8e9872df205b3f166f3098feecfab3ee8f6"
      define_method(:install) do
        bin.install "outfit"
      end
    end
  end

  test do
    system "#{bin}/outfit", "--help"
  end
end
